x=int (input("Enter nuber:"))
y=int (input("enter nuber:"))
print(x+y)
print(type(x))
print(type(y))
print("Addition=", x+y)
print("Subtraction=", x-y)
print("Multiplication=", x*y)
print("Division=", x/y)
print("X2 division=", x//y)
print("Exponent=" ,x**y)