import turtle
srn= turtle.Screen()
pen=turtle.Turtle()
pen.color("lavender")
pen.begin_fill()
pen.forward(200)
pen.right(90)
pen.forward(200)
pen.right(90)
pen.forward(200)
pen.right(90)
pen.forward(200)
pen.end_fill()
srn.exitonclick()