a= int (input("Enter number:"))
b= int (input("Enter number:"))
print(a+b)
print(type(a))
print(type(b))
print("Addition=", a+b)
print("Subtraction=", a-b)
print("Multiplication=", a*b)
print("Division=", a/b)
print("Division=", a//b)
print("exponent=" ,a**b)